//------------------------------------------------------------------------------
// <auto-generated>
//     這個程式碼是由範本產生。
//
//     對這個檔案進行手動變更可能導致您的應用程式產生未預期的行為。
//     如果重新產生程式碼，將會覆寫對這個檔案的手動變更。
// </auto-generated>
//------------------------------------------------------------------------------

namespace YungChing.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class memberSheet
    {
        public int uId { get; set; }
        public string uName { get; set; }
        public string uEmail { get; set; }
        public string uPassword { get; set; }
        public string uAddress { get; set; }
        public Nullable<int> uAge { get; set; }
        public string uGender { get; set; }
        public string uPhoto { get; set; }
    }
}
