//------------------------------------------------------------------------------
// <auto-generated>
//     這個程式碼是由範本產生。
//
//     對這個檔案進行手動變更可能導致您的應用程式產生未預期的行為。
//     如果重新產生程式碼，將會覆寫對這個檔案的手動變更。
// </auto-generated>
//------------------------------------------------------------------------------

namespace YungChing.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class 永慶房屋Entities : DbContext
    {
        public 永慶房屋Entities()
            : base("name=永慶房屋Entities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<commercialSheet> commercialSheet { get; set; }
        public virtual DbSet<houseSheet> houseSheet { get; set; }
        public virtual DbSet<likeSheet> likeSheet { get; set; }
        public virtual DbSet<memberSheet> memberSheet { get; set; }
    }
}
